stages:
  - build
  - deploy

build:
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  image: registry.gitlab.com/clairton/ci/builder:0.1.2
  script: 
    - build app
  artifacts:
    paths:
      - image_digest.txt
  only:
    - tags

deploy_dokku:
  image: dokku/ci-docker-image
  stage: deploy
  variables:
    GIT_REMOTE_URL: ssh://root@ssh.dokku.excellence.odo.br/chatwoot
    GIT_PUSH_FLAGS: '--force'
  script:
    - export BASE_CONTAINER_IMAGE="registry.gitlab.com/clairton/chatwoot/app"
    - export IMAGE_DIGEST=`cat image_digest.txt`
    - export DEPLOY_DOCKER_IMAGE="${BASE_CONTAINER_IMAGE}:${IMAGE_DIGEST}"
    - echo "deploy image ${DEPLOY_DOCKER_IMAGE}"
    - dokku-deploy
  only:
    - tags

deploy_production:
  stage: deploy
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  image: registry.gitlab.com/clairton/ci/deployer:0.1.1
  script:
    - deploy-heroku app chatwoot-w3b web $HEROKU_TOKEN
    - deploy-heroku app chatwoot-w3b worker $HEROKU_TOKEN
  only:
    - master