stages:
  - build
  - deploy

build:
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  image: registry.gitlab.com/clairton/ci/builder:0.1.1
  script: build app
  only:
    - tags

deploy_dokku:
  image: dokku/ci-docker-image
  stage: deploy
  variables:
    GIT_REMOTE_URL: ssh://root@ssh.dokku.excellence.odo.br/chatwoot
  script:
    - export TAG_NAME="$(git describe --abbrev=0 --tags | cut -d"v" -f2)"
    - export BASE_CONTAINER_IMAGE="registry.gitlab.com/clairton/chatwoot/app"
    - export DEPLOY_DOCKER_IMAGE="${BASE_CONTAINER_IMAGE}:${TAG_NAME}"
    - echo "deploy image ${DEPLOY_DOCKER_IMAGE}"
    - dokku-deploy
  only:
    - develop

deploy_production:
  stage: deploy
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  image: registry.gitlab.com/clairton/ci/deployer:0.1.1
  script:
    - deploy-heroku app chatwoot-w3b web $HEROKU_TOKEN
    - deploy-heroku app chatwoot-w3b worker $HEROKU_TOKEN
  only:
    - master