stages:
  - build
  - deploy

build:
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  image: registry.gitlab.com/clairton/ci/builder:0.1.1
  script: build app
  only:
    - tags

deploy_staging:
  stage: deploy
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  image: registry.gitlab.com/clairton/ci/deployer:0.1.1
  script:
    - deploy-heroku app chatwoot-app-staging web $HEROKU_TOKEN
    - deploy-heroku app chatwoot-app-staging worker $HEROKU_TOKEN
  only:
    - develop

deploy_production:
  stage: deploy
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  image: registry.gitlab.com/clairton/ci/deployer:0.1.1
  script:
    - deploy-heroku app chatwoot-w3b web $HEROKU_TOKEN
    - deploy-heroku app chatwoot-w3b worker $HEROKU_TOKEN
  only:
    - master