version: '3'

services:
  rails:
    build:
      dockerfile: rails.Dockerfile
    depends_on:
      - postgres
      - redis
    ports:
      - 3000:3000
    entrypoint: docker/entrypoints/rails.sh
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_PASSWORD: postgres
      RAILS_ENV: development
      RAILS_MAX_THREADS: 1

  sidekiq:
    build:
      dockerfile: sidekiq.Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_PASSWORD: postgres
      RAILS_ENV: development
      RAILS_MAX_THREADS: 1

  getmail:
    build:
      dockerfile: getmail.Dockerfile

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: chatwoot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: md5

  redis:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    env_file: .env
    volumes:
      - ./data/redis:/data
    ports:
      - '127.0.0.1:6379:6379'
