---
:mailboxes:
  -
    :host: <%= ENV['IMAP_HOST'] %>
    :port: <%= ENV['IMAP_PORT'] %>
    :email: <%= ENV['IMAP_USER'] %>
    :password: <%= ENV['IMAP_PASSWORD'] %>
    :ssl:  <%= ENV['IMAP_SSL'] %>
    :name: inbox
    :delivery_method: sidekiq
    :logger:
      :log_path: /app/relay/log
    :delivery_options:
      :redis_url:  <%= ENV['REDIS_URL'] %>
      :worker: EmailRelayJob