---
:mailboxes:
  -
    :email: <%= ENV['IMAP_USER'] %>
    :password: <%= ENV['IMAP_PASSWORD'] %>
    :name: inbox
    :delivery_method: postback
    :logger:
      :log_path: <%= ENV['CHATWOOT_LOG_PATH'].to_sym %>
    :delivery_options:
      :delivery_url:  <%= ENV['CHATWOOT_URL'] %>
      :username: <%= ENV['INGRESS_USER'] %>
      :password: <%= ENV['INGRESS_PASSWORD'] %>
      :content_type: message/rfc822
