---
:mailboxes:
  -
    :host: <%= ENV['IMAP_HOST'] %>
    :port: <%= ENV['IMAP_PORT'] %>
    :email: <%= ENV['IMAP_USER'] %>
    :password: <%= ENV['IMAP_PASSWORD'] %>
    :ssl:  <%= ENV['IMAP_SSL'] %>
    :name: inbox
    :delivery_method: postback
    :logger:
      :log_path: /app/relay/log
    :delivery_options:
      :delivery_url:  <%= ENV['CHATWOOT_URL'] %>
      :username: <%= ENV['INGRESS_USER'] %>
      :password: <%= ENV['INGRESS_PASSWORD'] %>
      :content_type: message/rfc822
