---
:mailboxes:
  -
    :email: "<%= ENV['IMAP_USER'] %>"
    :password: "<%= ENV['IMAP_PASSWORD'] %>"
    :name: "inbox"
    :host: "<%= ENV['IMAP_SERVER'] %>"
    :port: "<%= ENV['IMAP_PORT'] %>"
    :inbox_method: "IMAP"
    :search_command: "NEW"
    :delivery_method: "postback"
    :delivery_options:
      :delivery_url: "<%= ENV['CHATWOOT_URL'] %>/rails/action_mailbox/relay/inbound_emails"
      :delivery_username: "actionmailbox"
      :delivery_password: "<%= ENV['INGRESS_PASSWORD'] %>"
      :log_path: "STDOUT"