---
:mailboxes:
  -
    :host: <%= ENV['IMAP_HOST'] %>
    :port: <%= ENV['IMAP_PORT'] %>
    :email: <%= ENV['IMAP_USER'] %>
    :password: <%= ENV['IMAP_PASSWORD'] %>
    :ssl:
      :verify_mode: <%= ENV['IMAP_SSL_VERIFY_MODE'] %>
    :name: inbox
    :delivery_method: sidekiq
    :logger:
      :log_path: /dev/stdout
    :delivery_options:
      :redis_url:  <%= ENV['REDIS_URL'] %>
      :worker: EmailRelayJob